"""Wordmade ID Python SDK — agent identity for AI agents."""

from ._version import __version__
from .async_client import AsyncWordmadeID
from .client import WordmadeID
from .errors import (
    APIError,
    ForbiddenError,
    NotFoundError,
    RateLimitedError,
    UnauthorizedError,
    WordmadeIDError,
)
from .types import (
    Agent,
    AuthorizedApp,
    AuthorizedAppsResponse,
    AvatarResponse,
    CustomField,
    CustomFieldsResponse,
    DirectoryPage,
    DirectoryStats,
    MetadataEntry,
    MetadataListResponse,
    OAuthAuthorizeResult,
    OAuthDiscoveryResponse,
    OAuthTokenResponse,
    OAuthUserInfoResponse,
    ProfileUpdate,
    RecoverConfirmRequest,
    RecoverConfirmResponse,
    RecoverRequest,
    RegisterRequest,
    RegisterResponse,
    RegistryPage,
    RegistryParams,
    RotateKeyResponse,
    SearchParams,
    SessionResponse,
    Skill,
    SkillsResponse,
    TokenRequest,
    TokenResponse,
    VerifyResult,
    WellKnownField,
    WellKnownFieldsResponse,
    WorldPresence,
)

__all__ = [
    "__version__",
    "WordmadeID",
    "AsyncWordmadeID",
    "APIError",
    "ForbiddenError",
    "NotFoundError",
    "RateLimitedError",
    "UnauthorizedError",
    "WordmadeIDError",
    "Agent",
    "AuthorizedApp",
    "AuthorizedAppsResponse",
    "AvatarResponse",
    "CustomField",
    "CustomFieldsResponse",
    "DirectoryPage",
    "DirectoryStats",
    "MetadataEntry",
    "MetadataListResponse",
    "OAuthAuthorizeResult",
    "OAuthDiscoveryResponse",
    "OAuthTokenResponse",
    "OAuthUserInfoResponse",
    "ProfileUpdate",
    "RecoverConfirmRequest",
    "RecoverConfirmResponse",
    "RecoverRequest",
    "RegisterRequest",
    "RegisterResponse",
    "RegistryPage",
    "RegistryParams",
    "RotateKeyResponse",
    "SearchParams",
    "SessionResponse",
    "Skill",
    "SkillsResponse",
    "TokenRequest",
    "TokenResponse",
    "VerifyResult",
    "WellKnownField",
    "WellKnownFieldsResponse",
    "WorldPresence",
]
